### ISSUE TITLE
Text Size not working ?

### ISSUE THREAD

**Issue by SephVII** [suzaku01/mhf_displayer#5]
I noticed that changing text size doesnt do anything yet. I guess its not fully functional ? Or do i use it wrong ?

- v,1,4,1

**Comment by suzaku01** [comment]
It only works for display of damage text.

**Comment by SephVII** [comment]
> 

Oh i see yeah i dont use that thanks for letting me know xD ♥

**Comment by VictorChan7** [comment]
**1.42**  This problem occurs, the operation is not successful

System.ComponentModel.Win32Exception (0x80004005): Unable to enumerate the process modules.
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.Process.get_Modules()
   at mhf_displayer.Form1.Form1_Load(Object sender, EventArgs e) in F:\mhf_displayer-master\mhf_displayer\Form1.cs:line 53
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
